mytask/urls.py
from django.urls import path,include
from mytask import views


app_name= 'mytask'

urlpatterns = [
    path('',views.index,name='task'),
    path('update/<str:pk>/',views.updateTask,name='update'),
    path('delete/<str:pk>/',views.deleteTask,name='delete')

]

todo/urls.py
from django.contrib import admin
from django.urls import path,include
from mytask import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/',include('mytask.urls',namespace='mytask')),
]

mytask/models.py
from django.db import models


# Create your models here.
class Task(models.Model):
    task_name = models.CharField(max_length=256)
    complete = models.BooleanField(default=False)
    task_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.task_name

mytask/forms.py
from django import forms
from django.forms import ModelForm
from .models import *

class TaskForm(forms.ModelForm):
    task_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Add new task.....'}))
    class Meta():
        model = Task
        fields = '__all__'

mytask/views.py
from django.shortcuts import render,redirect
from django.views.generic import TemplateView,ListView
from . import models
from .forms import * 

# Create your views here.

def index(request):
    tasks = Task.objects.all()

    form = TaskForm()
    if request.method=='POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('mytask:task')

    context = {'tasks':tasks, 'form':form}

    return render(request,'mytask/list.html',context)

def updateTask(request,pk):
    task = Task.objects.get(id=pk)
    form = TaskForm(instance=task)

    if request.method=="POST":
        form = TaskForm(request.POST,instance=task)
        if form.is_valid():
            form.save()
        return redirect('mytask:task')
    context = {'form':form}   
    return render(request,'mytask/update_task.html',context)

def deleteTask(request,pk):
    item = Task.objects.get(id=pk)
    context = {'item':item}
    if request.method=="POST":
        item.delete()
        return redirect('mytask:task')

    return render(request,'mytask/delete.html',context)

mytask/templates/mytask/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.1/css/all.min.css">

<style>

	body{
		background-color: #638CB8;
	}

	input{
		width: 100%;
		padding: 12px 20px;
		margin: 8px 0;
		box-sizing: border-box;
	}

	input::placeholder {
	  color: #d3d3d3;
	}

	.submit{
		background-color: #6BA3E8;
	}

	.center-column{
		width:600px;
		margin: 20px auto;
		padding:20px;
		background-color: #fff;
		border-radius: 3px;
		box-shadow: 6px 2px 30px 0px rgba(0,0,0,0.75);
	}

	.item-row{
		background-color: #906abd;
		margin: 10px;
		padding: 20px;
		border-radius: 3px;
		color: #fff;
		font-size: 16px;
		box-shadow: 0px -1px 10px -4px rgba(0,0,0,0.75);
	}

	.btn-danger{
		background-color: #ffae19;
		border-color: #e59400;
	}

</style>

<title>TODO</title>
</head>
<body>

    {% block body_block %}
    {% endblock %}




<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.1/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/js/bootstrap.min.js"></script>
</body>
</html>

mytask/templates/mytask/delete.html
{% extends 'mytask/base.html' %}


{% block body_block  %}
<div class="center-column">

<p>Are you sure you want to delete? {{item}}</p>

<a class="btn btn-info" href="{% url 'mytask:task' %}">Cancel</a>
<form action="" method="POST">
    {% csrf_token %}
    <input class="submit" type="submit" name="Confirm" id="">
</form>

</div>

{% endblock  %}

mytask/templates/mytask/list.html
{% extends 'mytask/base.html' %}
{% block body_block %}
<div class="center-column">
    <h2 style="background-color:antiquewhite;">ToDo</h2>
    <form action="" method="POST">
        {% csrf_token %} {{form.task_name}}
        <input class="btn btn-info" type="submit" value="submit" />
    </form>


    {% for task in tasks %}
    <div class="item-row">
        <li class="list-unstyled">{{task}}</li>
        <a class="btn btn-sm btn-info" href="{% url 'mytask:update' task.id %}">Update</a>
        <a class="btn btn-sm btn-danger" href="{% url 'mytask:delete' task.id %}">Delete</a>
        {% if task.complete == True %}
        <strike>{{task}}</strike>
        {% else %}
        <span>{{task}}</span>
        {% endif %}
    </div>
    {% endfor%}

</div>
</div>
{% endblock %}

mytask/templates/mytask/update_task.html
{% extends 'mytask/base.html' %}


{% block body_block %}
<div class="center-column">

<h1>Update Task</h1>
<form action="" method="POST" >
    {% csrf_token %}
    {{form}}
    <input type="Submit" name="" id="">
</form>
</div>
{% endblock %}